name: Audit Students

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      APP: http://127.0.0.1:3000
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      ADMIN_BEARER_TOKEN: ${{ secrets.ADMIN_BEARER_TOKEN }}
      PATTERN: Seeded Student %

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: edurebel-app/package-lock.json

      - name: Install deps
        working-directory: edurebel-app
        run: npm ci

      - name: Write .env.local
        working-directory: edurebel-app
        run: |
          cat > .env.local <<EOF
          NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
          SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
          ADMIN_BEARER_TOKEN=${ADMIN_BEARER_TOKEN}
          EOF

      - name: Build
        working-directory: edurebel-app
        run: npm run build

      - name: Start Next
        working-directory: edurebel-app
        run: |
          nohup npx next start -p 3000 > .next/ci.log 2>&1 &
          echo $! > .next/ci.pid

      - name: Wait for Next
        run: bash edurebel-app/scripts/ci-wait-for-next.sh "$APP/api/health" 60

      - name: Doctor
        working-directory: edurebel-app
        run: APP="$APP" bash scripts/doctor.sh

      - name: Audit (global)
        working-directory: edurebel-app
        run: make -s audit PATTERN="$PATTERN"

      - name: Audit (since 24h)
        working-directory: edurebel-app
        run: make -s audit-since PATTERN="$PATTERN" HOURS=24

      - name: JSON report
        working-directory: edurebel-app
        run: make -s seed-report-json PATTERN="$PATTERN" | tee tmp/seed-report-ci.json

      - name: Export sample CSV
        working-directory: edurebel-app
        run: make -s export-students PATTERN='%25' LIMIT=5 ORDER=created_at.desc OUT='tmp/students-sample-ci.csv'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: audit-artifacts
          path: |
            edurebel-app/.next/ci.log
            edurebel-app/tmp/seed-report-ci.json
            edurebel-app/tmp/students-sample-ci.csv
          if-no-files-found: warn

      - name: Stop Next
        if: always()
        working-directory: edurebel-app
        run: '[ -f .next/ci.pid ] && kill $(cat .next/ci.pid) || true'
